version: '3.1'
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    volumes: 
       - ./content:/var/lib/ghost/content
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      # Your url site
      url: https://joaonotfound.com

  db:
    image: mysql:8.0
    restart: always
    volumes:    
     - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
