version: "3.1"
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./content:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${PASSWORD}
      database__connection__database: ghost
      url: ${DOMAIN}

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
